### ISSUE TITLE
Bug when use in new elixir version (1.12)

### ISSUE THREAD

**Issue by DaanKrug** [Schultzer/sntp#1]
20:16:43.500 [error] Task #PID<0.524.0> started from ExApp.Supervisor terminating
** (UndefinedFunctionError) function nil.__struct__/0 is undefined
    nil.__struct__()
    (elixir 1.12.0) lib/kernel.ex:2303: Kernel.struct/3
    (sntp 0.2.1) lib/sntp/socket.ex:39: SNTP.Socket.new/1
    (sntp 0.2.1) lib/sntp.ex:107: SNTP.time/1

The problem is in module socket.ex, in method "new".
Replacing the **@struct** by the official documentation way to
obtain a struct **struct(SNTP.Struct)** it worked.

@spec new(Enumerable.t()) :: t()
  def new(opts \\ []) do
    opts = validate_opts(opts)
    #@struct
    struct(SNTP.Struct)
    |> Kernel.struct(opts)
    |> open()
  end

defmodule SNTP.Struct do
  
  alias SNTP.NTPMessage
 
  defstruct [
    errors: [],
    host: 'pool.ntp.org',
    host_port: 123,
    message: %NTPMessage{},
    port: nil,
    resolve_reference: false,
    timeout: :infinity,
    is_valid?: false
  ]
end

**Comment by Schultzer** [comment]
The reason for this is due to a name change of the module attribute: https://github.com/elixir-lang/elixir/issues/10352 and https://github.com/elixir-lang/elixir/pull/10354.

To answer the question why using `@struct`? Is because it's compiled, using `struct(SNTP.Struct)` would introduce runtime penalties.

A solution might be to define a `@struct` module attribute like: `@struct @__struct__`.

This would need to be tested if it's backwards compatible.
